# Generated by Django 5.2 on 2025-05-06 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('sobrenome', models.CharField(blank=True, max_length=120)),
                ('apelido', models.CharField(blank=True, max_length=70)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('chave_pix', models.CharField(max_length=500)),
                ('data_criada', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
