# Generated by Django 5.2 on 2025-05-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/%Y/%m', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='show',
            field=models.BooleanField(default=True, verbose_name='mostrar'),
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoria'),
        ),
    ]
