# Generated by Django 5.2 on 2025-05-07 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_criada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servico',
            name='show',
            field=models.BooleanField(default=True, verbose_name='mostrar'),
        ),
    ]
