# Generated by Django 5.2 on 2025-05-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_servico_data_criada_servico_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbeiro',
            old_name='categoria',
            new_name='categoria_user',
        ),
    ]
