# Generated by Django 5.2 on 2025-05-07 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_categoria_barbeiro_categoria_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.CreateModel(
            name='CategoriaUser',
            fields=[
                ('categoria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.categoria')),
            ],
            bases=('home.categoria',),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoriaservico'),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='categoria_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.categoriauser'),
        ),
    ]
